name: EggWars
version: @version@
main: com.ryan.eggwars.EggWars
api-version: 1.16
author: Ryan
description: idk a game for kings

commands:
  join:
    description: Join a team.
  
  leave:
    description: Leaves your team.
  
  eggwars:
    description: Various commands for eggwars.
    
  gen:
    description: Creates a generator.
    
  eggtool:
    description: Random tools.